query ($owner: String!, $repo: String!, $number: Int!) {
  repository(owner: $owner, name: $repo) {
    pullRequest(number: $number) {
      createdAt
      body
      timelineItems(last: 1, itemTypes: [READY_FOR_REVIEW_EVENT]) {
        nodes {
          ... on ReadyForReviewEvent {
            createdAt
          }
        }
      }
      userContentEdits(first: 20) {
        nodes {
          editedAt
          editor {
            login
          }
        }
      }
      comments(last: 100) {
        totalCount
        pageInfo {
          hasPreviousPage
          startCursor
        }
        nodes {
          id
          author {
            login
          }
          body
          createdAt
          updatedAt
        }
      }
      reviews(last: 100) {
        nodes {
          state
          author {
            login
          }
          body
          submittedAt
          commit {
            oid
          }
        }
      }
      reviewThreads(first: 100) {
        nodes {
          isResolved
          comments(first: 1) {
            nodes {
              body
              author {
                login
              }
            }
          }
          latest: comments(last: 1) {
            nodes {
              author {
                login
              }
            }
          }
        }
      }
      commits(last: 100) {
        totalCount
        nodes {
          commit {
            oid
            committedDate
            checkSuites(first: 100) {
              nodes {
                createdAt
                app {
                  slug
                }
              }
            }
            statusCheckRollup {
              contexts(first: 100) {
                pageInfo {
                  hasNextPage
                  endCursor
                }
                nodes {
                  __typename
                  ... on CheckRun {
                    name
                    status
                    conclusion
                    title
                    startedAt
                    completedAt
                    checkSuite {
                      createdAt
                    }
                  }
                  ... on StatusContext {
                    context
                    state
                    createdAt
                    description
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
