query($owner: String!, $repo: String!, $number: Int!) {
  repository(owner: $owner, name: $repo) {
    pullRequest(number: $number) {
      createdAt
      timelineItems(last: 1, itemTypes: [READY_FOR_REVIEW_EVENT]) {
        nodes { ... on ReadyForReviewEvent { createdAt } }
      }
      comments(last: 100) { nodes { author { login } body createdAt updatedAt } }
      reviews(last: 100) { nodes { author { login } state body commit { oid } } }
      reviewThreads(first: 100) {
        nodes {
          isResolved
          comments(first: 1) { nodes { author { login } body originalCommit { oid } } }
        }
      }
      commits(last: 100) {
        nodes {
          commit {
            oid
            committedDate
            checkSuites(first: 100) { nodes { createdAt } }
            statusCheckRollup {
              contexts(first: 100) {
                nodes {
                  __typename
                  ... on CheckRun { name status title }
                  ... on StatusContext { context state description }
                }
              }
            }
          }
        }
      }
    }
  }
}
