#!/bin/sh
set -eu

script=$0
case "$script" in
  */*) ;;
  *) script=./$script ;;
esac

while [ -L "$script" ]; do
  target=$(readlink "$script")
  case "$target" in
    /*) script=$target ;;
    *) script=${script%/*}/$target ;;
  esac
done

directory=$(CDPATH= cd -P "${script%/*}" && pwd)
exec bun --no-env-file "$directory/../../src/evals/gh.ts" "$@"
